### PR TITLE
submit PR

### PR DESCRIPTION
**Pull request by contract-dev-bk**
submit PR

### CODE REVIEW

**Comment by panora-exchange** [comment]
Thank you for raising the PR. Could you also kindly post a tweet from the official X handle of Tomarket, tagging @PanoraExchange? This will help verify the authenticity and ensure we don't list an incorrect token address.

**Comment by contract-dev-bk** [comment]
> Thank you for raising the PR. Could you also kindly post a tweet from the official X handle of Tomarket, tagging @PanoraExchange? This will help verify the authenticity and ensure we don't list an incorrect token address.

Sorry,Our official Twitter has been temporarily suspended recently, and we hope to use media or Telegram announcements to verify our identity, is that ok?

**Comment by panora-exchange** [comment]
sure, that works. Please share the links with us once updated on your other official social channels / telegram.

**Comment by contract-dev-bk** [comment]
> sure, that works. Please share the links with us once updated on your other official social channels / telegram.

Here, https://medium.com/@tomarket/toma-panoraexchange-verification-834134848074
please check this

**Comment by panora-exchange** [comment]
Updated. Dedicated link - https://app.panora.exchange/swap/aptos?pair=APT-TOMA

**Comment by contract-dev-bk** [comment]
Sorry, the Icon on explorer is not clear, please check and update to .svg file from my commit.https://explorer.aptoslabs.com/coin/0x9d0595765a31f8d56e1d2aafc4d6c76f283c67a074ef8812d8c31bd8252ac2c3::asset::TOMA?network=mainnet

**Comment by contract-dev-bk** [comment]
> Updated. Dedicated link - https://app.panora.exchange/swap/aptos?pair=APT-TOMA

Sorry, the Icon on explorer is not clear, please check and update to .svg file from my commit.https://explorer.aptoslabs.com/coin/0x9d0595765a31f8d56e1d2aafc4d6c76f283c67a074ef8812d8c31bd8252ac2c3::asset::TOMA?network=mainnet

**Pull request closed without merging**
